/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoback;
import com.mycompany.projetoback.DAO.SessoesDeFilmesDao;
import controller.TelaDeSessõesController;
import controller.TelaDePoltronaController;
import com.mycompany.projetoback.DAO.SessãoDao;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
/**
 *
 * @author pedro
 */
public class TelaDeSessões extends javax.swing.JFrame {
    private String filme;
    private final SessoesDeFilmesDao s;
    private final SessãoDao p;
    private ArrayList<Integer> id;
    private int codigo;
    /**
     * Creates new form TelaDeSessões
     */
    public TelaDeSessões() {
        initComponents();
        s = new SessoesDeFilmesDao();
        p = new SessãoDao();
        id = new ArrayList();
        
    }
    public void ExportarNome(TelaDeSessõesController t){
        lbl.setText(t.getFilme());
        setFilme(lbl.getText());
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel1 = new com.mycompany.projetoback.loginPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sessoes = new javax.swing.JComboBox<>();
        sss = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel1.setBackground(new java.awt.Color(255, 0, 0));
        loginPanel1.setImg(new ImageIcon("C:\\Users\\pedro\\Documents\\NetBeansProjects\\JavaApplication2\\src\\com\\mycompany\\imagens\\tela vermalha.png"));
        loginPanel1.setLayout(null);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        loginPanel1.add(jButton2);
        jButton2.setBounds(80, 330, 90, 23);

        jButton1.setText("Avançar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginPanel1.add(jButton1);
        jButton1.setBounds(270, 330, 90, 23);

        loginPanel1.add(sessoes);
        sessoes.setBounds(70, 210, 326, 22);

        sss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sss.setText("Sessões:");
        loginPanel1.add(sss);
        sss.setBounds(70, 160, 55, 20);

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginPanel1.add(lbl);
        lbl.setBounds(60, 60, 203, 68);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPoltronas t = new TelaPoltronas();
        TelaDePoltronaController tela = new TelaDePoltronaController();
        //t.verificaPoltronas(t.pesquisaPoltrona(this.retornaSessão(),this.retornaHorario()));
        tela.setId(this.getId().get(this.sessoes.getSelectedIndex()));
        t.exportarValor(tela);
        //t.buscaSessão(tela.getId());
        t.setVisible(true);
        this.dispose();
        //System.out.println(this.getId());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeSessões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeSessões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeSessões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeSessões.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeSessões().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl;
    private com.mycompany.projetoback.loginPanel loginPanel1;
    private javax.swing.JComboBox<String> sessoes;
    private javax.swing.JLabel sss;
    // End of variables declaration//GEN-END:variables
    public void listaSessoes(){
        for(int i = 0; i<s.ler().size();i++){
            if(s.ler().get(i).getFilme().equals(filme)){
                this.sessoes.addItem(s.ler().get(i).getSessao()+" "+s.ler().get(i).getHorario());   
                id.add(s.ler().get(i).getId());
            }
        }
        System.out.println(filme);
    }
    /*public String retornaSessão(){
        for(int i = 0; i<s.ler().size();i++){
            if(s.ler().get(i).getFilme().equals(filme)){
                return (s.ler().get(i).getSessao());   
            }
        }
        return null;
    }
    public String retornaHorario(){
        for(int i = 0; i<s.ler().size();i++){
            if(s.ler().get(i).getFilme().equals(filme)){
                return (s.ler().get(i).getHorario());   
            }
        }
        return null;
    }
    public int retornaId(String sessão, String horario){
        for(int i = 0;i<p.ler().size();i++){
            if(p.ler().get(i).getNome().equals(sessão) && p.ler().get(i).getHorario().equals(horario)){
                   return p.ler().get(i).getId();
            }
        }
        return 0;
    }*/
    
    public void exportarCodigo(TelaDeSessõesController t){
        t.setCodigo(this.getCodigo());
    }
    public String getFilme() {
        return filme;
    }

    public void setFilme(String filme) {
        this.filme = filme;
    }

    public ArrayList<Integer> getId() {
        return id;
    }

    public void setId(ArrayList<Integer> id) {
        this.id = id;
    }

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    
}
