/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.projetoback;
import com.mycompany.projetoback.DAO.AdmDAO;
import com.mycompany.projetoback.DAO.Banco;
import com.mycompany.projetoback.DAO.AdmDAO;
import java.util.ArrayList;
/**
 *
 * @author silvio
 */
public class TelaFilmes extends javax.swing.JFrame {
    AdmDAO d;
    Banco b;
    /**
     * Creates new form TelaFilmes
     */
    public TelaFilmes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbImgTelaFilme3 = new javax.swing.JLabel();
        lbImgTelaFilme4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbImgTelaFilme2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        horarios = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();

        jPanel1.setLayout(null);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        lbImgTelaFilme3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projetoback/Imagens/a chegada r.jpg"))); // NOI18N
        getContentPane().add(lbImgTelaFilme3);
        lbImgTelaFilme3.setBounds(130, 230, 100, 150);

        lbImgTelaFilme4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projetoback/Imagens/no contry for old men r.jpg"))); // NOI18N
        getContentPane().add(lbImgTelaFilme4);
        lbImgTelaFilme4.setBounds(440, 230, 110, 150);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 150, 37, 16);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 220, 37, 16);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(650, 290, 37, 16);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 380, 72, 23);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(660, 360, 37, 16);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(650, 30, 37, 16);

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Horário");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 380, 40, 16);

        lbImgTelaFilme2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projetoback/Imagens/donnie darko r.jpg"))); // NOI18N
        getContentPane().add(lbImgTelaFilme2);
        lbImgTelaFilme2.setBounds(440, 20, 110, 150);

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 90, 43, 16);

        jLabel13.setText("Horário");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 170, 40, 10);

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Horário");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(160, 160, 40, 30);

        jLabel15.setText("Horário");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(160, 380, 40, 16);

        getContentPane().add(horarios);
        horarios.setBounds(140, 190, 72, 22);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projetoback/Imagens/the room r.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(130, 30, 110, 130);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        d = new AdmDAO();
        String nome = "Donnie darko";
        
        ArrayList<String> s = new ArrayList(); 
        s= d.buscarSessão(nome);
        System.out.println(s.get(0));
        for(int i = 0;i<s.size();i++){
            horarios.addItem(s.get(i));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> horarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImgTelaFilme2;
    private javax.swing.JLabel lbImgTelaFilme3;
    private javax.swing.JLabel lbImgTelaFilme4;
    // End of variables declaration//GEN-END:variables
}
