/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoback;
import com.mycompany.projetoback.DAO.AdmDAO;
import java.util.List;
import javax.swing.JOptionPane;
import com.mycompany.projetoback.DAO.SessãoDao;
import com.mycompany.projetoback.DAO.AdmDAO;
import com.mycompany.projetoback.Sessão;
import com.mycompany.projetoback.Filme;
import com.mycompany.projetoback.SessõesDeFilmes;
import com.mycompany.projetoback.DAO.SessoesDeFilmesDao;
import java.util.ArrayList;
import connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
/**
 *
 * @author pedro
 */
public class TelasDefilmes extends javax.swing.JFrame {
    SessãoDao dao = new SessãoDao();
    Sessão Sdao;
    AdmDAO d = new AdmDAO();
    SessoesDeFilmesDao l;
    ArrayList<Integer> index;
    /**
     * Creates new form TelasDefilmes
     */
    public TelasDefilmes() {
        initComponents();
        listaFilmes();
        listaHorarios();
        listaSessoes();
        l = new SessoesDeFilmesDao();
        index = new ArrayList();
        this.listaSessões();
        
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        loginPanel1 = new com.mycompany.projetoback.loginPanel();
        jLabel2 = new javax.swing.JLabel();
        sessoesBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        filmesBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        horarioBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        sessoesFilmes = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        adiciona = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel1.setImg(new ImageIcon("C:\\Users\\pedro\\Documents\\NetBeansProjects\\JavaApplication2\\src\\com\\mycompany\\imagens\\Pesquisar Filmes.png"));

        jLabel2.setText("Sessões:");

        sessoesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessoesBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Filmes:");

        jLabel3.setText("Horario:");

        jLabel4.setText("Sessoes de Filme:");

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        adiciona.setText("Adicionar");
        adiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Adicionar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Remover");

        javax.swing.GroupLayout loginPanel1Layout = new javax.swing.GroupLayout(loginPanel1);
        loginPanel1.setLayout(loginPanel1Layout);
        loginPanel1Layout.setHorizontalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addGap(327, 327, 327)
                .addComponent(jLabel4))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(sessoesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238)
                .addComponent(sessoesFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(filmesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298)
                .addComponent(jButton2))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(horarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(adiciona, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginPanel1Layout.setVerticalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessoesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessoesFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filmesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(horarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(adiciona)
                .addGap(117, 117, 117)
                .addComponent(jButton3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaActionPerformed
        Filme f;
        String filme = filmesBox.getSelectedItem().toString();
        f = d.buscaFilme(filme);
        String horario = horarioBox.getSelectedItem().toString();
        String sessao = sessoesBox.getSelectedItem().toString();
        Sdao = new Sessão(sessao,horario);
        Sdao.getListaDeFilmes().add(f);
        dao.criarPoltronas(Sdao);
        dao.create(Sdao);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = index.get(sessoesFilmes.getSelectedIndex());
        System.out.println(id);
        this.remover(id);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sessoesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessoesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessoesBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelasDefilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelasDefilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelasDefilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelasDefilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelasDefilmes().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adiciona;
    private javax.swing.JComboBox<String> filmesBox;
    private javax.swing.JComboBox<String> horarioBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private com.mycompany.projetoback.loginPanel loginPanel1;
    private javax.swing.JComboBox<String> sessoesBox;
    private javax.swing.JComboBox<String> sessoesFilmes;
    // End of variables declaration//GEN-END:variables

        public void listaFilmes(){
        for(int i = 0; i<d.listarFilmes().size();i++){
            this.filmesBox.addItem(d.listarFilmes().get(i));
            
        }
        }

        public void listaSessoes(){
        for(int i = 0; i<d.listarSessoes().size();i++){
            this.sessoesBox.addItem(d.listarSessoes().get(i));
            
        }
        }
        public void listaHorarios(){
        for(int i = 0; i<d.listarSessoes().size();i++){
            this.horarioBox.addItem(d.listarHorarios().get(i));
        }
        }
        
        public void listaSessões(){
            for(int i = 0;i<l.ler().size();i++){
                sessoesFilmes.addItem(l.ler().get(i).getFilme()+" "+l.ler().get(i).getSessao()+" "+l.ler().get(i).getHorario());
                index.add(l.ler().get(i).getId());
            }
        }
        public void remover(int id){
            Connection con = ConnectionFactory.getConnection();
            PreparedStatement stmt = null;
            
            try {
                stmt = con.prepareStatement("DELETE FROM sessoes WHERE id = ?");
                stmt.setInt(1,id);
                stmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "atualizado Com Sucesso");
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "Erro ao atualizar" + ex);
                }finally{
                    ConnectionFactory.closeConnection(con, stmt);
            }
            }
        }
 


