/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoback;

import com.mycompany.projetoback.DAO.ClienteDao;
import controller.TelaDeFinalizaçãoController;
import java.util.ArrayList;
import java.sql.Connection;
import connection.ConnectionFactory;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import controller.popUpCompraController;
/**
 *
 * @author pedro
 */
public class TelaDeFinalização extends javax.swing.JFrame {
    private int id;
    private int numeroPoltronas;
    private ArrayList<Boolean> poltronas;
    
    /**
     * Creates new form TelaDeFinalização
     */
    public TelaDeFinalização() {
        initComponents();
        poltronas = new ArrayList();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel2 = new com.mycompany.projetoback.loginPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxInteira = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxCombo = new javax.swing.JComboBox<>();
        cbxMeia = new javax.swing.JComboBox<>();
        consulta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel2.setImg(new ImageIcon("C:\\Users\\pedro\\Documents\\NetBeansProjects\\JavaApplication2\\src\\com\\mycompany\\imagens\\Finalização de Pedidos.png"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("Ingressos");

        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("R$ 26,00");

        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("R$ 13,00");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Inteira:");

        cbxInteira.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Meia:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Valor Total");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setText("Combos:");

        cbxCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opções", "R$ 15 - Chocolate e Refrigerante 10%Desconto", "R$ 20 - Pipoca e Refrigerante 15%Desconto", "R$ 25 - Pipoca, Chocolate e Refrigerante 20%Desconto" }));
        cbxCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComboActionPerformed(evt);
            }
        });

        cbxMeia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 ", "1", "2", "3", " " }));

        consulta.setText("Consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout loginPanel2Layout = new javax.swing.GroupLayout(loginPanel2);
        loginPanel2.setLayout(loginPanel2Layout);
        loginPanel2Layout.setHorizontalGroup(
            loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel2Layout.createSequentialGroup()
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanel2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(loginPanel2Layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbxCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbxInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbxMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanel2Layout.createSequentialGroup()
                                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jButton2)))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        loginPanel2Layout.setVerticalGroup(
            loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxInteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(cbxMeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int inteiraValor = cbxInteira.getSelectedIndex();
            int meiaValor = cbxMeia.getSelectedIndex();
            int ingresso = inteiraValor + meiaValor;
            
            if(ingresso > 3){
                JOptionPane.showMessageDialog(rootPane, "Não é possível comprar mais de três ingressos");
            } else{
                this.atualizaPoltronas(this.getId(),this.getPoltronas()); 
                popUpCompraController p = new popUpCompraController();
                p.setValor(total.getText());
                p.setId(this.getId());
                p.setCombo(this.cbxCombo.getSelectedItem().toString());
                PopUpCompraRealizada confirmar = new PopUpCompraRealizada();
                confirmar.exportarValor(p);
                confirmar.valoresSelecionados();
                confirmar.selecionaFilmes();
                confirmar.setVisible(true);
                this.dispose();
                
            }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
            int inteira = cbxInteira.getSelectedIndex();
            int meia = cbxCombo.getSelectedIndex();
            String combo = cbxCombo.getSelectedItem().toString();
            int valorinteira = inteira * 26;
            int valormeia = meia * 13;
            int valorTotal = valorinteira + valormeia;                    
            int ingresso = inteira + meia;
     
            if(ingresso <= 3 && "R$ 15 - Chocolate e Refrigerante 10%Desconto".equals(combo)){
                total.setText("R$ " + (valorTotal - (valorTotal * 0.1)));
            } else if(ingresso <= 3 && "R$ 20 - Pipoca e Refrigerante 15%Desconto".equals(combo)){
                total.setText("R$ " + (valorTotal - (valorTotal * 0.15)+20));
            } else if (ingresso <= 3 && "R$ 25 - Pipoca, Chocolate e Refrigerante 20%Desconto".equals(combo)){
                total.setText("R$ " + (valorTotal - (valorTotal * 0.2)+25));
            }else{
                total.setText("R$ " + valorTotal);
            }
           
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaActionPerformed

    private void cbxComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalização.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalização.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalização.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFinalização.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFinalização().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCombo;
    private javax.swing.JComboBox<String> cbxInteira;
    private javax.swing.JComboBox<String> cbxMeia;
    private javax.swing.JButton consulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.mycompany.projetoback.loginPanel loginPanel2;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
    public void atualizaPoltronas(int id, ArrayList<Boolean> lista){
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt  = null;
        try {
            stmt = con.prepareStatement("UPDATE poltronas SET poltrona1=?,poltrona2=?,poltrona3=?,poltrona4=?,poltrona5=?,poltrona6=?,poltrona7=?,poltrona8=?,poltrona9=?,poltrona10=?,poltrona11=?,poltrona12=?,poltrona13=?,poltrona14=?,poltrona15=?,poltrona16=?,poltrona17=?,poltrona18=?,poltrona19=?,poltrona20=?,poltrona21=?,poltrona22=?,poltrona23=?,poltrona24=?,poltrona25=?,poltrona26=?,poltrona27=?,poltrona28=? WHERE id =? ");
            
            stmt.setBoolean(1, lista.get(0));
            stmt.setBoolean(2, lista.get(1));
            stmt.setBoolean(3, lista.get(2));
            stmt.setBoolean(4, lista.get(3));
            stmt.setBoolean(5, lista.get(4));
            stmt.setBoolean(6, lista.get(5));
            stmt.setBoolean(7, lista.get(6));
            stmt.setBoolean(8, lista.get(7));
            stmt.setBoolean(9, lista.get(8));
            stmt.setBoolean(10, lista.get(9));
            stmt.setBoolean(11, lista.get(10));
            stmt.setBoolean(12, lista.get(11));
            stmt.setBoolean(13, lista.get(12));
            stmt.setBoolean(14, lista.get(13));
            stmt.setBoolean(15, lista.get(14));
            stmt.setBoolean(16, lista.get(15));
            stmt.setBoolean(17, lista.get(16));
            stmt.setBoolean(18, lista.get(17));
            stmt.setBoolean(19, lista.get(18));
            stmt.setBoolean(20, lista.get(19));
            stmt.setBoolean(21, lista.get(20));
            stmt.setBoolean(22, lista.get(21));
            stmt.setBoolean(23, lista.get(22));
            stmt.setBoolean(24, lista.get(23));
            stmt.setBoolean(25, lista.get(25));
            stmt.setBoolean(26, lista.get(26));
            stmt.setBoolean(27, lista.get(27));
            stmt.setBoolean(28, lista.get(28));
            stmt.setInt(29,id);
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "compra realizada com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "falha na compra seu imbecil!");
            Logger.getLogger(ClienteDao.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            ConnectionFactory.closeConnection(con, stmt);
        }
            
    }
   //public int calcularTotalInteira(){
       //int i =0;
       //int pchocolate = (Integer)chocolate.getValue();
       //int prefrigerante = (Integer)refrigerante.getValue();
       //int ppipoca = (Integer)pipoca.getValue();
       //i = (this.getNumeroPoltronas()*20)+pchocolate+prefrigerante+ppipoca;
     //  return i;
   //}
   //public int calculaTotalMeia(){
     //  int i =0;
   //    int pchocolate = (Integer)chocolate.getValue();
 //     int prefrigerante = (Integer)refrigerante.getValue();
       //int ppipoca = (Integer)pipoca.getValue();
      // i = (this.getNumeroPoltronas()*10)+pchocolate+prefrigerante+ppipoca;
     //  return i;
   //}

    public int getNumeroPoltronas() {
        return numeroPoltronas;
    }
  
    public void setNumeroPoltronas(int numeroPoltronas) {
        this.numeroPoltronas = numeroPoltronas;
    }
    
    public void calculaValorTotal(){
        int i = this.getNumeroPoltronas()*26;
        total.setText(""+i);
    }
    
    public void exportarValor(TelaDeFinalizaçãoController t){
       this.setId(t.getId());
       this.setNumeroPoltronas(t.getPoltronas());
       this.setPoltronas(t.getListaDepoltronas());
       //ingressos.setText(String.valueOf(this.getNumeroPoltronas()));
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ArrayList<Boolean> getPoltronas() {
        return poltronas;
    }

    public void setPoltronas(ArrayList<Boolean> poltronas) {
        this.poltronas = poltronas;
    }
    
}
